# -*- coding: utf-8 -*-
"""SPESA-OFF-NTB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVmrtkaLaqH7SuQ3jzekej8_flbde0LA
"""

# !pip install langchain_community

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qU langchain-community pypdf

from langchain_community.document_loaders import PyPDFLoader
import pprint
import re
import os
from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
# import faiss
import numpy as np
import pickle
from langchain_community.document_loaders import UnstructuredExcelLoader
from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct
from dotenv import load_dotenv
load_dotenv()
def read_excel(filepath):
  loader = UnstructuredExcelLoader(filepath, mode="elements")
  docs = loader.load()

  return docs[0].page_content


## remove delimiter while writing the modular code
def load_pdf_content(filepath):
  loader = PyPDFLoader(
      filepath,
      mode = "single",
      # pages_delimiter="\n ---------- ---- ----This is end of page ---------------"
  )

  docs = loader.load()
  content = docs[0].page_content
  return content

# print(content)



def format_text(content):
  content = content.replace("'\n","\n")
  content = content.replace("'","")
  content = re.sub(r'\n{2,}', '\n\n', content)
  content = content.replace("'","")
  content = content.replace("\n \n","\n")
  content = content.strip()
  return content

# pdf_content = format_text(content)

# print(pdf_content)

def load_web_content(address):
  web_loader = WebBaseLoader(address)

  web_docs = web_loader.load()
  content = web_docs[0].pagecontent
  return content

def cut_after(content,word):
  return content.split(word,1)[0]

def cut_before(content,word):
  return content.split(word,1)[1]

# print(pdf_content)

def make_sections(content):
  sections = []

  curr_heading = None
  curr_content = []
  for line in content.split("\n"):
    if re.match(r'^(\$\.)',line.strip()):
      if curr_heading:
        sections.append({
            "heading":curr_heading,
            "content":"\n".join(curr_content).strip()
        })
      curr_heading=line.strip()
      curr_content=[]
    else:
      curr_content.append(line)

  if curr_heading:
      sections.append({
          "heading": curr_heading,
          "content": "\n".join(curr_content).strip()
      })

  return sections

# pdf_sections = make_sections(pdf_content)

"""## Making chunks -> Embedding -> Vector storage is pending

"""


text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=20)

def make_chunks(sections,start):
  final_chunks=[]
  j=start
  for section in sections:
    chunkable_txt = section['content']
    chunks = text_splitter.split_text(chunkable_txt)
    for i, chunk in enumerate(chunks):
      final_chunks.append({
          "heading": section["heading"],
          "chunk_id": j,
          "chunk" : chunk
      }
      )
      j+=1
  return final_chunks

# pdf_chunks= make_chunks(pdf_sections)

# !pip install sentence-transformers faiss-cpu

# cont_to_embed = [chunk["chunk"] for chunk in pdf_chunks]
def encod_chunks(cont_to_encod,model_name):
  encoder = SentenceTransformer(model_name)

  embeddings = encoder.encode(
      cont_to_encod,
      normalize_embeddings=True,
      batch_size=32,
      show_progress_bar=True
  )
  return embeddings

qdrant_client = QdrantClient(
    url=os.getenv("QDRANT_URL"), 
    api_key=os.getenv("QDRANT_API_KEY"),
)
# print(embedding.shape[1])
# len(pdf_chunks)
def add_to_index_storage(embeddings,chunks,collection_name):
  dim = embeddings.shape[1]
  points = [
    PointStruct(
        id=chunk["chunk_id"],   # unique ID
        vector=embedding,       # embedding vector
        payload={
            "text": chunk["chunk"]
        }
    )
    for chunk, embedding in zip(chunks, embeddings)
  ]

  qdrant_client.upsert(
      collection_name=collection_name,
      points=points
  )
  # base_index = faiss.IndexFlatIP(dim)
  # index = faiss.IndexIDMap(base_index)
  # ids_l =[chunk["chunk_id"] for chunk in chunks]
  # ids = np.array(ids_l)
  # with open("metadata/chunks_text/chunk_metadata.txt", "w", encoding="utf-8") as f:
  #     for id in ids:
  #         chunk_id = chunks[id]["chunk_id"]
  #         chunk_text = chunks[id]["chunk"]
  #         f.write(f"(({chunk_id})) - {chunk_text}\n")
  # index.add_with_ids(np.array(embeddings),ids)
  # return index

# query_emb = encoder.encode("is your product trustworthy", normalize_embeddings=True, )
# query_emb = query_emb.reshape(1, -1)

# D, I = index.search(query_emb, k=3)

# print(pdf_chunks[I[0][0]])
def export_index_file(index_name, custom_name):
  faiss.write_index(index_name, f"index_files/{custom_name}.index")

def export_chunks(chunks,file_name):
  with open(f"data/chunks/pkl_of_chunks_{file_name}.pkl","wb") as f:
    pickle.dump(chunks,f)

# export_chunks(pdf_chunks)

# content = load_pdf_content("Sample ecom.pdf")
# format_content = format_text(content)
# sections = make_sections(format_content)
# chunks = make_chunks(sections)
# embeddings = encod_chunks("BAAI/bge-small-en-v1.5",chunks)
# index_file = add_to_faiss_storage(embeddings)
# export_index_file(index_file,"sample")
# export_chunks(chunks)