# -*- coding: utf-8 -*-
"""SPES-AI-ONL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WoYuGviZpjTxF2N0qW4jJyG7k5eFyEB
"""

# !pip install langchain-community faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import pickle
# from src.components.main import to_online

def emb_query(user_query):
  encoder = SentenceTransformer("BAAI/bge-small-en-v1.5") #dont use name of encoder directly, use a variable here and call it from somewhere else
  user_inp_emb = encoder.encode(
      user_query,
      normalize_embeddings=True
  )
  return user_inp_emb

def take_user_query(query):
  embedded_query = emb_query(query)
  return embedded_query

def reqd_dataset(I,chunks,i):
  reqd_data = chunks[I[0][i]]
  return reqd_data


def run(user_query):
  query = [user_query]

  index = faiss.read_index("sample.index")


  emb_user_query = take_user_query(query)
  D, I = index.search(emb_user_query, k=3)

  with open("chunks_folder/pkl_of_chunks.pkl","rb") as f:
    chunks = pickle.load(f)



  dataset_parts = []

  for i in range(1):
      item = reqd_dataset(I,chunks,i)
      dataset_parts.append(item["chunk"])

  dataset = "\n".join(dataset_parts)
  return dataset

